FoodApp/urls.py
from FoodApp import views
from django.urls import path

app_name='FoodApp'
urlpatterns = [
    path('',views.home,name='home'),
    path('<int:item_id>/',views.details,name='details'),
    path('add/',views.add_item,name='additem'),
    path('update/<int:id>/',views.update_item,name='update'),
    path('delete/<int:id>/',views.delete_item,name='delete'),
]

FoodProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('FoodApp.urls')),
    path('users/',include('users.urls')),
    path('',views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),

]

users/urls.py
from users import views
from django.urls import path

app_name='users'
urlpatterns = [
    path('register/',views.register,name='reg'),
    path('profile/',views.profile,name='profile'),
]

FoodApp/models.py
from django.db import models

# Create your models here.
class Items(models.Model):
    item_name=models.CharField(max_length=122)
    item_desc=models.CharField(max_length=122)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=5000,default='https://t4.ftcdn.net/jpg/03/16/15/47/360_F_316154790_pnHGQkERUumMbzAjkgQuRvDgzjAHkFaQ.jpg')

users/models.py
from django.db import models

# Create your models here.

FoodApp/forms.py
from django import forms
from .models import Items

class ItemForm(forms.ModelForm):
    class Meta:
        model=Items
        fields=['item_name','item_desc','item_price','item_image']

FoodApp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Items
from FoodApp.forms import ItemForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def home(request):
    item_list=Items.objects.all()
    context={
        'item_list':item_list
    }
    return render(request,'FoodApp/home.html',context)

def details(request,item_id):
    item_list=Items.objects.get(pk=item_id)
    context={
        'item_list':item_list
    }
    return render(request,'FoodApp/details.html',context)

def add_item(request):
    form=ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('FoodApp:home')
    return render(request,'FoodApp/item-form.html',{'form':form})

def update_item(request,id):
    item=Items.objects.get(pk=id)
    form=ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('FoodApp:home')
    return render(request,'FoodApp/item-form.html',{'form':form})

def delete_item(request,id):
    item=Items.objects.get(pk=id)
    if request.method=='POST':
        item.delete()
        return redirect('FoodApp:home')
    return render(request,'FoodApp/delete_msg.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm

def register(request):
    form=UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('login')
    return render(request,'users/register.html',{'form':form})

def profile(request):
    return render(request,'users/profile.html')

FoodApp/templates/FoodApp/base.html
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    />
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a
            class="navbar-brand"
            href="{% url 'FoodApp:home' %}"
            style="font-weight: bold"
            >FoodApp</a
          >
        </div>
        <ul class="nav navbar-nav">
          <li><a href="{% url 'users:profile' %}">Profile</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
      </div>
    </nav>
    {% block body %}
    
    {% endblock %}
  </body>
</html>

FoodApp/templates/FoodApp/delete_msg.html
{% extends "FoodApp/base.html" %}
{% block body %}
<form method='POST'>
    {% csrf_token %}
    <h1> Are you sure you want to delete this item {{item.item_name}}?</h1>
    <img src="{{item.item_image}}"
    height="300px"
      class="card"
      style="border-radius: 50px; 
      border: 5px solid black"
    /> <br><br><br>
    <button 
    style='background-color:grey;
    padding:10px;
    color:black;
    border:2px solid black;
    border-radius:10px;
    margin-left:200px'>CONFIRM</button>
</form>
{% endblock %}

FoodApp/templates/FoodApp/details.html
{% extends "FoodApp/base.html" %} {% block body %}

<div class="row">
    <div class='col-md-2'></div>
  <div class="col-md-6">
    <img
      src="{{item_list.item_image}}"
      height="300px"
      class="card"
      style="border-radius: 50px; 
      border: 5px solid black"
    />

    <h1>{{item_list.item_name}}</h1>
    {{item_list.item_desc}}
    <br /><br />
    <b>Rs.{{item_list.item_price}}</b>
  </div>

    <div class="col-md-2">
<a href={% url 'FoodApp:additem'%} class="btn btn-success" 
style="background-color:grey;">ADD ITEM </a>
<br><br>

<a href={% url 'FoodApp:delete' item_list.id %} class="btn btn-success" 
style="background-color:grey;">DELETE ITEM</a>
<br><br>

<a href={% url 'FoodApp:update' item_list.id %} class="btn btn-success" 
style="background-color:grey;">UPDATE ITEM</a>

    </div>
  </div>
</div>
{% endblock %}

FoodApp/templates/FoodApp/home.html
{% extends "FoodApp/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item List</title>
</head>
<body>
    {% block body %}
    {% for i in item_list %}
<div class='row'>
<div class='col-md-2'></div>
<div class='col-md-4'>
    <img class='card' src={{i.item_image}} height=150px>
</div>
<br><br>
<div class='col-md-3' style='font-family:cursive;font-weight:bold;font-size:20px'>{{i.item_name}}</div>

<div class='col-md-2'>
    <a href={% url 'FoodApp:details' i.id %} class="btn btn-success" style="background-color:black;" >
        Details
    </a>
</div>
</div>
<br><br>
{% endfor %}
{% endblock %}
</body>
</html>

FoodApp/templates/FoodApp/item-form.html
{% extends "FoodApp/base.html" %} 
{% block body %}
<form method='POST'>
    {% csrf_token %}
    {{form}}
    <button>SUBMIT</button>
</form>
{% endblock %}

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kodnest Business app Login Page</title>
    <style>
        body {
            margin: 0;
            padding: 0;
        }
        .form-container {
            background-color: orange;
            font-family: cursive;
            font-weight: bold;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .form-group input {
            border: 2px solid;
            width: 100%;
            padding: 15px;
            box-sizing: border-box;
            border-radius: 12px;
            margin: 9px;
        }
        .form-container form {
            background-color: white;
            width: 400px;
            border-radius: 10px;
            box-shadow: 2px 2px 3px grey;
            text-align: center;
            padding: 30px;
        }
        .form-container form a {
            text-decoration: none;
            color: black;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 12px;
            margin-left: 9px;
            display: inline-block;
            margin-top: 20px; /* Adjust as needed */
            text-align: center;
            padding: 10px 20px;
            background-color: orangered;
            border-radius: 12px;
            transition: background-color 0.3s ease;
        }
        .form-container form a:hover {
            background-color: darkorange;
        }
        .form-container form button {
            width: 100%;
            background-color: orangered;
            border: none;
            padding: 9px;
            border-radius: 9px;
            color: white;
            font-weight: bold;
            font-family: cursive;
            margin: 4px;
        }
        .form-container input[type='email']:focus + label {
            position: absolute;
            margin-top: -69px;
            margin-left: 15px;
            background-color: white;
        }
        .form-container input[type='email']:not(:focus) + label,
        .form-container input[type='password']:not(:focus) + label {
            display: none;
        }
        .form-container input[type='password']:focus + label {
            margin-top: -70px;
            margin-left: 18px;
            position: absolute;
            background-color: white;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class='form-group'>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <input type="hidden" name="next" value="{% url 'FoodApp:home' %}">
            <p>Don't have an account? <a href="{% url 'users:reg' %}" class="register-link">Register</a></p>
            <button type='submit'>Login</button>
        </form>
    </div>
</body>
</html>

users/templates/users/logout.html
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .message-container {
        max-width: 400px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        text-align: center;
    }
</style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'FoodApp:home' %}" style='font-weight:bold'>FoodApp</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Profile</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
          </ul>
        </div>
      </nav>
      <div class="message-container">
        <h3>You've been Successfully Logged Out. </h3>
            <h4>See You Next Time!</h4>
    </div>
      {% block body %}
      {% endblock %}
</body>
</html>

users/templates/users/profile.html
{% extends "FoodApp/base.html" %}
{% block body %}
<h1>Profile Page </h1>
<h3>{{user.username}}</h3>
{% endblock %}

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        .form-container {
            background-color: orange;
            font-family: cursive;
            font-weight: bold;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .form-group input {
            border: 2px solid;
            width: 100%;
            padding: 15px;
            box-sizing: border-box;
            border-radius: 12px;
            margin: 9px;
        }
        .form-container form {
            background-color: white;
            width: 400px;
            border-radius: 10px;
            box-shadow: 2px 2px 3px grey;
            text-align: center;
            padding: 30px;
        }
        .form-container form a {
            text-decoration: none;
            color: black;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 12px;
            margin-left: 9px;
            display: inline-block;
            margin-top: 20px; /* Adjust as needed */
            text-align: center;
            padding: 10px 20px;
            background-color: orangered;
            border-radius: 12px;
            transition: background-color 0.3s ease;
        }
        .form-container form a:hover {
            background-color: darkorange;
        }
        .form-container form button {
            width: 100%;
            background-color: orangered;
            border: none;
            padding: 9px;
            border-radius: 9px;
            color: white;
            font-weight: bold;
            font-family: cursive;
            margin: 4px;
        }
        .form-container input[type='email']:focus + label {
            position: absolute;
            margin-top: -69px;
            margin-left: 15px;
            background-color: white;
        }
        .form-container input[type='email']:not(:focus) + label,
        .form-container input[type='password']:not(:focus) + label {
            display: none;
        }
        .form-container input[type='password']:focus + label {
            margin-top: -70px;
            margin-left: 18px;
            position: absolute;
            background-color: white;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class='form-group'>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <button type='submit'>Register</button>
        </form>
    </div>
</body>
</html>